services:
  api:
    build: ./api
    working_dir: /app/src/utf_case
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./api/src:/app/src
      - ./api/tests:/app/tests
      - ./api/pytest.ini:/app/pytest.ini
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app/src
      DJANGO_SETTINGS_MODULE: utf_case.config.settings
      POSTGRES_DB: utf_case
      POSTGRES_USER: utf_case_user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  ui:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: utf_case
      POSTGRES_USER: utf_case_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utf_case_user -d utf_case"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: